[package]
name = "fyroxed-c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
fyroxed_base = { workspace = true }
fyrox = { workspace = true }
fyrox-c-lib = { workspace = true }
